#!/bin/sh
# Pre-commit hook placeholder
# Version is now determined by commit hash at build time (not pre-commit)
# See scripts/build/update-version.js

# No-op - hook exists but does nothing
exit 0
